defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Manuel Montalvan
subtitle: Full-Stack Developer

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Mi Perfil
    link: /
    icon: ""

  - text: Ingenier√≠a de Software
    link: /skills-and-offers
    icon: ""

  - text: Contactos
    link: /contact
    icon: ""

  - text: Mi Resumen
    link: /resume
    icon: ""

  - text: Blog 
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  

  - name: github
    link: https://manuelmontalvan.github.io/
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/manuel.montalvan.92/
    icon: fab fa-facebook-square

  - name: twitter
    link: https://twitter.com/BillsKC17
    icon: fab fa-twitter


    
